// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user_wire

// Injectors from wire.go:

func InitializeUserService(foo string, bar int) *UserService {
	mockUserRepo := NewMockUserRepo(foo, bar)
	userService := NewUserService(mockUserRepo)
	return userService
}
