definitions:
  user.User:
    properties:
      email:
        type: string
      passwordHash:
        type: string
      phoneNum:
        type: string
      role:
        description: 角色：admin、guest、register、vip、vip2
        type: string
      status:
        type: string
      userId:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/profile:
    get:
      consumes:
      - application/json
      description: 根据用户ID获取用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: 请求参数错误
          schema: {}
        "500":
          description: 服务器内部错误
          schema: {}
      summary: 获取用户个人信息
      tags:
      - 用户相关
swagger: "2.0"
